services:
  - type: web
    name: hasin-portfolio
    runtime: docker
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Hasin Portfolio
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://hasin-portfolio.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: PORT
        value: "80"
      - key: WEBROOT
        value: /var/www/html/public
      - key: RUN_SCRIPTS
        value: "1"
      - key: REAL_IP_HEADER
        value: "1"
      - key: SKIP_COMPOSER
        value: "1"
      - key: PHP_CATCHALL
        value: "1"
